apiVersion: apps/v1
kind: Deployment
metadata:
  name: d1
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  myapp
  template:
    metadata:
      name: p1
      labels:
        app:  myapp
    spec:
      containers:
      - name: c1
        image:  nehakumbharde/mygame
        ports:
        - containers: 80
          name: nginx-port
          protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80
